apiVersion: v1
kind: Service
metadata:
  labels:
    service: react
  name: react
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    service: react
  type: LoadBalancer
status:
  loadBalancer: {}
