apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    service: react
  name: react
spec:
  selector:
    matchLabels:
      service: react
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: react
    spec:
      containers:
        - name: react
          image: appliedblockchain/launchpad-react:latest
          ports:
            - containerPort: 80
          # env:
          #   - name: NODE_ENV
          #     value: staging
          resources: {}
      hostname: launchpad-react
      imagePullSecrets:
        - name: regcred
      terminationGracePeriodSeconds: 1
      # restartPolicy: Always
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
